version: '3'

services:
  spring-webshop-db:
    image: "mysql/mysql-server"
    container_name: "spring-webshop-db"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

  spring-webshop-backend:
    build: ./
    container_name: "spring-webshop-backend"
    environment:
      - MYSQL_DB=${DB_NAME}
      - MYSQL_SERVER=spring-webshop-db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_PORT=3306
    ports:
      - "8080:8080"
    depends_on:
      spring-webshop-db:
        condition: service_healthy