package com.jorgeparavicini.springwebshop.database.repositories

import com.jorgeparavicini.springwebshop.database.entities.RecommendedProduct

interface RecommendedProductRepository : BaseRepository<RecommendedProduct>